### ISSUE TITLE
Erro ao tentar executar o exemplo `condicional.libra`

### ISSUE THREAD

**Issue by fabiosvm** [lucasdcampos/libra#4]
Obtive o seguinte erro o tentar executar o exemplo `condicional.libra`.

**Erro: Impossível determinar expressão na linha 1**

Veja a imagem:

![image](https://github.com/user-attachments/assets/ac5d2072-8fb1-4444-97dc-0cf3ff72cc86)

O conteúdo do arquivo é o seguinte:

```
se 1 > 0 entao
    sair(1)
fim

sair(0)
```

A sintaxe está ok?

**Comment by lucasdcampos** [comment]
Sintaxe está ok. Problema já foi corrigido.

![image](https://github.com/user-attachments/assets/1b33599e-3c7d-4385-bc9f-af93345c1722)
